# Generated by Django 2.1.7 on 2019-03-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_color', models.CharField(max_length=100, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('birth_city', models.CharField(max_length=100, null=True)),
                ('favorite_social_media_platform', models.CharField(max_length=100, null=True)),
                ('road', models.CharField(max_length=100, null=True)),
                ('favorite_food', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
            },
        ),
    ]
