# Generated by Django 2.1.5 on 2019-01-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('residencehalls', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hallway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencehalls.Hallway'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencehalls.ResidenceHall'),
        ),
        migrations.AddField(
            model_name='student',
            name='resident_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ResidentAssistant'),
        ),
        migrations.AddField(
            model_name='student',
            name='roommates',
            field=models.ManyToManyField(related_name='_student_roommates_+', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencehalls.Suite'),
        ),
        migrations.AddField(
            model_name='student',
            name='suitemates',
            field=models.ManyToManyField(related_name='_student_suitemates_+', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentassistant',
            name='residence_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencehalls.ResidenceHall'),
        ),
        migrations.AddField(
            model_name='residentassistant',
            name='suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencehalls.Suite'),
        ),
        migrations.AddField(
            model_name='residentassistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='halldirector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
