# Generated by Django 2.1.5 on 2019-01-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190119_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cell_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_one_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_one_primary_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_one_relationship_to_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_two_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_two_primary_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_two_relationship_to_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_street_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medications_or_special_needs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_assistance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
