# Generated by Django 2.1.5 on 2019-01-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Hallway',
                'verbose_name_plural': 'Hallways',
            },
        ),
        migrations.CreateModel(
            name='ResidenceHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('hall_director', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.HallDirector')),
            ],
            options={
                'verbose_name': 'Residence Hall',
                'verbose_name_plural': 'Residence Halls',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hallway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencehalls.Hallway')),
            ],
            options={
                'verbose_name': 'Suite',
                'verbose_name_plural': 'Suites',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencehalls.Suite'),
        ),
        migrations.AddField(
            model_name='hallway',
            name='residence_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencehalls.ResidenceHall'),
        ),
        migrations.AddField(
            model_name='hallway',
            name='resident_assistant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ResidentAssistant'),
        ),
    ]
