# Generated by Django 2.1.5 on 2019-01-29 02:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.CharField(default='', max_length=10, null=True, verbose_name='date of birth')),
                ('cell_phone_number', models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='cell phone number')),
                ('home_street_address', models.CharField(default='', max_length=100, null=True, verbose_name='home street address')),
                ('home_city', models.CharField(default='', max_length=100, null=True, verbose_name='home city')),
                ('home_state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('American Samoa', 'American Samoa'), ('District of Columbia', 'District of Columbia'), ('Federated States of Micronesia', 'Federated States of Micronesia'), ('Guam', 'Guam'), ('Marshall Islands', 'Marshall Islands'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Palau', 'Palau'), ('Puerto Rico', 'Puerto Rico'), ('Virgin Islands', 'Virgin Islands')], default='', max_length=100, null=True, verbose_name='home state')),
                ('zip_code', models.IntegerField(null=True, verbose_name='zip code')),
                ('allergies', models.TextField(default='', null=True, verbose_name='allergies')),
                ('physical_assistance', models.BooleanField(default=False)),
                ('medications_or_special_needs', models.TextField(default='', null=True, verbose_name='medications or special needs')),
                ('emergency_contact_one_name', models.CharField(default='', max_length=30, null=True, verbose_name='name of emergency contact one')),
                ('emergency_contact_one_relationship_to_student', models.CharField(default='', max_length=20, null=True, verbose_name='relationship of emergency contact one to student')),
                ('emergency_contact_one_primary_phone_number', models.CharField(default='', max_length=17, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='primary phone number of emergency contact one')),
                ('emergency_contact_two_name', models.CharField(default='', max_length=30, null=True, verbose_name='name of emergency contact two')),
                ('emergency_contact_two_relationship_to_student', models.CharField(default='', max_length=20, null=True, verbose_name='relationship of emergency contact two to student')),
                ('emergency_contact_two_primary_phone_number', models.CharField(default='', max_length=17, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='primary phone number of emergency contact two')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
