# Generated by Django 2.1.5 on 2019-01-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinformationcard',
            options={'verbose_name': 'Student Information Card', 'verbose_name_plural': 'Student Information Cards'},
        ),
    ]
